### ISSUE TITLE
Soft hyphen causing a blank line before the widget

### ISSUE THREAD

**Issue by Rowno** [h5bp/html5please-api#64]
I don't know if this is intentional, but there's a `&shy;` at the start of the API html output. This is causing an unnecessary blank line to appear before the widget in my page layout.

**Comment by paulirish** [comment]
that's http://www.thecssninja.com/javascript/noscope in action.. for the $shy;

but

there is no reason it should  add a new line. :/

**Comment by Rowno** [comment]
You can see it happening on this page in IE <=9. http://rowno.github.com/architect/

If you remove the soft hyphen using the developer tools, you'll notice that the extra line disappears.

**Comment by Rowno** [comment]
Would it be possible to just move the `<style>` tag to after all the other html? According to [this thread on MSDN](http://social.msdn.microsoft.com/forums/en-US/iewebdevelopment/thread/33fd33f7-e857-4f6f-978e-fd486eba7174/) it solves the problem as well.

**Comment by paulirish** [comment]
cc @ryanseddon you heard of this?

**Comment by ryanseddon** [comment]
Well a soft hyphen in theory will do a line break where needed but will remain invisible otherwise, it just happens that IE treats the following div as a continuation of the text and then says well there's not enough room for both so I'll break here. 

However this can easily be fixed by setting the .caniuse div to be `display: inline-block` and setting `width: 100%`. Or we can fix this right in the API by not even including the soft hyphen but by making the html come before the style. That will work the same as a soft hyphen.

**Comment by paulirish** [comment]
Cool. I'll do the latter.

Thanks Ryan

**Comment by drublic** [comment]
I've changed the order of HTML and CSS in the API's output. The `&shy;` is no longer part of it.

I've tested this in IE7, 8 and 9. Works for me with the tests in `tests/test.html`. Could you please try and test this again? Thanks.

**Comment by paulirish** [comment]
Thank you Hans!

**Comment by Rowno** [comment]
It's working fine for me as well. :)
